In [18]:
from sklearn.datasets import fetch_mldata
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
import numpy as np

In [13]:
iris = fetch_mldata('iris')

In [32]:
X,y = iris["data"], iris["target"]
train_size = 100

X_train, X_test, y_train, y_test = X[:train_size], X[train_size:], y[:train_size], y[train_size:]

shuffle_index = np.random.permutation(train_size)

X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]

y_train_1 = (y_train == 1)
y_test_1 = (y_test ==1)

sgd_clf = SGDClassifier(random_state = 42, max_iter = 1000, tol = 1e-3)
sgd_clf.fit(X_train, y_train_1)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=1000, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=0.001, verbose=0, warm_start=False)

In [16]:
cross_val_score(sgd_clf,X_train,y_train_1,cv=3,scoring='accuracy')

array([ 1.     ,  1.     ,  0.90625])

In [19]:
y_train_pred = cross_val_predict(sgd_clf,X_train,y_train_1,cv=3)

In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train_1, y_train_pred)

array([[47,  3],
       [ 0, 50]], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
precision_score(y_train_1, y_train_pred)

0.94339622641509435

In [24]:
recall_score(y_train_1, y_train_pred)

1.0

In [25]:
f1_score(y_train_1, y_train_pred)

0.970873786407767

In [31]:
accuracy_score(y_train_1, y_train_pred)

0.96999999999999997

In [37]:
y_test_pred = sgd_clf.predict(X_test)

In [38]:
accuracy_score(y_test_1,y_test_pred)

1.0

In [39]:
f1_score(y_test_1, y_test_pred)

0.0

In [40]:
recall_score(y_test_1, y_test_pred)

0.0

In [41]:
y_test_pred

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False], dtype=bool)

In [42]:
y_test_1

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False], dtype=bool)